export default {
    success: 'success',
    selects: document.querySelectorAll('.select'),
    amountInput: document.getElementById('amount'),
    form: document.querySelector('.form'),
    formInfo: document.querySelector('.form-info__results'),
    lastTime: document.querySelector('.rate-information__last'),
    resultFrom: document.getElementById('resultFrom'),
    resultTo: document.getElementById('resultTo'),
    rateConv: document.querySelector('.rate-information__convertion'),
    timeLoad: document.querySelector('.rate-information__last'),
    switchButton: document.querySelector('.switch-currency'),
    toSelect: document.getElementById('to'),
    fromSelect: document.getElementById('from'),
    tabs: document.querySelectorAll('.tab'),
    currentCurrency: document.querySelector('.currency-wrapper-single__item'),
    currentCurrencyList: document.querySelector('.currency-wrapper__list'),
    singleSelect: document.getElementById('singleSelect'),
    addButton: document.querySelector('.currency-add__button'),
    addCurrencySelect: document.getElementById('addCurrencySelect'),
};